"""test

Revision ID: bbeeb589267d
Revises: afc09de52fcd
Create Date: 2023-02-20 15:42:20.088903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeeb589267d'
down_revision = 'afc09de52fcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('batches', sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_lines', sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_lines', sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_lines', 'ts_modify')
    op.drop_column('order_lines', 'ts_create')
    op.drop_column('batches', 'ts_modify')
    op.drop_column('batches', 'ts_create')
    # ### end Alembic commands ###
